[package]
name = "rustgtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk-sys = "0.17.0"
gdk = "0.17.1"
glib = "0.17.9"
gtk = { version = "0.17.0" }
